CREATE TABLE app_users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 display_name VARCHAR(80) NOT NULL
);
CREATE TABLE projects (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_id BIGINT NOT NULL REFERENCES app_users(id),
 name VARCHAR(100) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX projects_owner_idx ON projects(owner_id);
CREATE TABLE tasks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES projects(id),
 title VARCHAR(200) NOT NULL,
 description VARCHAR(4000) NOT NULL,
 priority VARCHAR(10) NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
 due_date DATE,
 completed BOOLEAN NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX tasks_project_completed_idx ON tasks(project_id, completed);
CREATE INDEX tasks_project_due_idx ON tasks(project_id, due_date);
CREATE TABLE refresh_sessions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES app_users(id),
 token_hash VARCHAR(64) NOT NULL UNIQUE,
 family_id VARCHAR(36) NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 revoked BOOLEAN NOT NULL
);
CREATE INDEX refresh_family_idx ON refresh_sessions(family_id);
