import { test, expect } from '@playwright/test';
test('register, project/task CRUD, filters, profile, refresh and user isolation', async ({ page, browser }) => {
  const email = 'user-' + Date.now() + '@example.com';
  await page.goto('/');
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByLabel('Display name', { exact: true }).fill('Windy');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('StrongPassword123!');
  await page.getByRole('button', { name: 'Create account →' }).click();
  await expect(page.getByRole('heading', { name: 'All your next steps' })).toBeVisible();
  await expect(page.getByRole('link', { name: /Manage users/ })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeInViewport();
  await page.getByLabel('New project name').fill('Career');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Career', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'New task' }).click();
  await page.getByLabel('Task title').fill('Learn deployments');
  await page.getByLabel('Description', { exact: true }).fill('Practice EC2 and GitHub Actions');
  await page.getByLabel('Priority', { exact: true }).selectOption('HIGH');
  await page.getByRole('button', { name: 'Save task' }).click();
  await expect(page.getByRole('button', { name: 'Learn deployments', exact: true })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Complete Learn deployments' }).click();
  await expect(page.getByRole('button', { name: 'Learn deployments', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: /All tasks/ }).click();
  await expect(page.getByRole('button', { name: 'Learn deployments', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: /Completed/ }).click();
  await expect(page.getByRole('button', { name: 'Learn deployments', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Completed tasks', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Learn deployments', exact: true }).click();
  await page.getByLabel('Task title').fill('Deploy with confidence');
  await page.getByRole('button', { name: 'Save task' }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toBeVisible();
  await page.getByLabel('Search tasks').fill('no-match');
  await expect(page.getByText('No completed tasks here yet.')).toBeVisible();
  await page.getByLabel('Search tasks').fill('');
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeInViewport();
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/workspace-mobile.png', fullPage: true });
  await page.getByRole('link', { name: /Windy/ }).click();
  await page.getByLabel('Display name').fill('Windy Updated');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await expect(page.getByRole('link', { name: /Windy Updated/ })).toBeVisible();
  await page.getByRole('link', { name: 'Career' }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: /Completed/ }).click();
  await page.getByRole('checkbox', { name: 'Restore Deploy with confidence' }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'Career' }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Complete Deploy with confidence' }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'New task' }).click();
  await page.getByLabel('Task title').fill('Still active');
  await page.getByRole('button', { name: 'Save task' }).click();
  await expect(page.getByRole('button', { name: 'Still active', exact: true })).toBeVisible();
  page.on('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete project', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Career', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Still active', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: /Completed/ }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toHaveCount(0);
  const otherContext = await browser.newContext();
  const other = await otherContext.newPage();
  await other.goto('http://localhost:15173');
  await expect(other.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await otherContext.close();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('StrongPassword123!');
  await page.getByRole('button', { name: 'Sign in →' }).click();
  await expect(page.getByRole('link', { name: /Windy Updated/ })).toBeVisible();
});

test('admin manages accounts and invalidates reset/deleted sessions', async ({ page, browser }) => {
  const email = 'managed-' + Date.now() + '@example.com', updatedEmail = 'edited-' + email;
  await page.goto('/');
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByLabel('Display name', { exact: true }).fill('Managed User');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('StrongPassword123!');
  await page.getByRole('button', { name: 'Create account →' }).click();
  await expect(page.getByRole('heading', { name: 'All your next steps' })).toBeVisible();
  await page.goto('/#/admin');
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible();
  await page.getByLabel('New project name').fill('Private project');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Private project', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'New task' }).click();
  await page.getByLabel('Task title').fill('Private task');
  await page.getByRole('button', { name: 'Save task' }).click();
  await expect(page.getByRole('button', { name: 'Private task', exact: true })).toBeVisible();

  const adminContext = await browser.newContext(), admin = await adminContext.newPage();
  await admin.goto('http://localhost:15173');
  await admin.getByLabel('Email', { exact: true }).fill('admin@qq.com');
  await admin.getByLabel('Password', { exact: true }).fill('admin');
  await admin.getByRole('button', { name: 'Sign in →' }).click();
  await expect(admin.getByRole('heading', { name: 'All your next steps' })).toBeVisible();
  await expect(admin.getByRole('button', { name: 'Private task', exact: true })).toHaveCount(0);
  await admin.getByRole('link', { name: /Manage users/ }).click();
  await admin.getByLabel('Search users').fill('admin@qq.com');
  await expect(admin.getByRole('button', { name: 'Delete account admin@qq.com', exact: true })).toBeDisabled();
  await admin.getByLabel('Search users').fill(email);
  await admin.getByRole('button', { name: 'Edit account ' + email, exact: true }).click();
  const editor = admin.getByRole('dialog', { name: 'Edit account' });
  await editor.getByLabel('Display name').fill('Updated User');
  await editor.getByLabel('Email', { exact: true }).fill(updatedEmail);
  await editor.getByLabel('New password').fill('NewStrongPassword123!');
  await editor.getByRole('button', { name: 'Save account' }).click();
  await expect(editor).toHaveCount(0);
  await admin.getByLabel('Search users').fill(updatedEmail);
  await expect(admin.getByRole('article', { name: 'Account ' + updatedEmail, exact: true })).toContainText('Updated User');
  await admin.setViewportSize({ width: 390, height: 844 });
  expect(await admin.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await admin.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });

  await page.getByRole('link', { name: /Completed/ }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill(updatedEmail);
  await page.getByLabel('Password', { exact: true }).fill('NewStrongPassword123!');
  await page.getByRole('button', { name: 'Sign in →' }).click();
  await expect(page.getByRole('link', { name: /Updated User/ })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Private project', exact: true })).toBeVisible();
  admin.on('dialog', dialog => dialog.accept());
  await admin.getByRole('button', { name: 'Delete account ' + updatedEmail, exact: true }).click();
  await expect(admin.getByText('Account and workspace deleted.')).toBeVisible();
  await expect(admin.getByRole('article', { name: 'Account ' + updatedEmail, exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: /All tasks/ }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill(updatedEmail);
  await page.getByLabel('Password', { exact: true }).fill('NewStrongPassword123!');
  await page.getByRole('button', { name: 'Sign in →' }).click();
  await expect(page.getByRole('alert')).toContainText('Invalid credentials or expired session');
  await adminContext.close();
});
