import { test, expect } from '@playwright/test';
test('register, project/task CRUD, filters, profile, refresh and user isolation', async ({ page, browser }) => {
  const email = 'user-' + Date.now() + '@example.com';
  await page.goto('/');
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByLabel('Display name', { exact: true }).fill('Windy');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('StrongPassword123!');
  await page.getByRole('button', { name: 'Create account →' }).click();
  await expect(page.getByRole('heading', { name: 'All your next steps' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeInViewport();
  await page.getByLabel('New project name').fill('Career');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Career', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'New task' }).click();
  await page.getByLabel('Task title').fill('Learn deployments');
  await page.getByLabel('Description', { exact: true }).fill('Practice EC2 and GitHub Actions');
  await page.getByLabel('Priority', { exact: true }).selectOption('HIGH');
  await page.getByRole('button', { name: 'Save task' }).click();
  await expect(page.getByRole('button', { name: 'Learn deployments', exact: true })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Complete Learn deployments' }).click();
  await expect(page.getByRole('checkbox', { name: 'Complete Learn deployments' })).toBeChecked();
  await page.getByLabel('Filter status').selectOption('true');
  await expect(page.getByRole('button', { name: 'Learn deployments', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Career', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Learn deployments', exact: true }).click();
  await page.getByLabel('Task title').fill('Deploy with confidence');
  await page.getByRole('button', { name: 'Save task' }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toBeVisible();
  await page.getByLabel('Search tasks').fill('no-match');
  await expect(page.getByText('A little breathing room.')).toBeVisible();
  await page.getByLabel('Search tasks').fill('');
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeInViewport();
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/workspace-mobile.png', fullPage: true });
  await page.getByRole('link', { name: /Windy/ }).click();
  await page.getByLabel('Display name').fill('Windy Updated');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await expect(page.getByRole('link', { name: /Windy Updated/ })).toBeVisible();
  await page.getByRole('link', { name: 'Career' }).click();
  page.on('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete Deploy with confidence', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Deploy with confidence', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Delete project', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Career', exact: true })).toHaveCount(0);
  const otherContext = await browser.newContext();
  const other = await otherContext.newPage();
  await other.goto('http://localhost:15173');
  await expect(other.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await otherContext.close();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('StrongPassword123!');
  await page.getByRole('button', { name: 'Sign in →' }).click();
  await expect(page.getByRole('link', { name: /Windy Updated/ })).toBeVisible();
});
